/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables;


import github.spritecn.swaggerTest.repository.DefaultSchema;
import github.spritecn.swaggerTest.repository.Keys;
import github.spritecn.swaggerTest.repository.tables.records.TaskRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task extends TableImpl<TaskRecord> {

    private static final long serialVersionUID = -1409384039;

    /**
     * The reference instance of <code>task</code>
     */
    public static final Task TASK = new Task();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskRecord> getRecordType() {
        return TaskRecord.class;
    }

    /**
     * The column <code>task.id</code>.
     */
    public final TableField<TaskRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>task.last_update_time</code>.
     */
    public final TableField<TaskRecord, Long> LAST_UPDATE_TIME = createField(DSL.name("last_update_time"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>task.request_body</code>.
     */
    public final TableField<TaskRecord, String> REQUEST_BODY = createField(DSL.name("request_body"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>task.fail_count</code>.
     */
    public final TableField<TaskRecord, Integer> FAIL_COUNT = createField(DSL.name("fail_count"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>task.pass_count</code>.
     */
    public final TableField<TaskRecord, Integer> PASS_COUNT = createField(DSL.name("pass_count"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>task.start_time</code>.
     */
    public final TableField<TaskRecord, Long> START_TIME = createField(DSL.name("start_time"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>task.end_time</code>.
     */
    public final TableField<TaskRecord, Long> END_TIME = createField(DSL.name("end_time"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>task</code> table reference
     */
    public Task() {
        this(DSL.name("task"), null);
    }

    /**
     * Create an aliased <code>task</code> table reference
     */
    public Task(String alias) {
        this(DSL.name(alias), TASK);
    }

    /**
     * Create an aliased <code>task</code> table reference
     */
    public Task(Name alias) {
        this(alias, TASK);
    }

    private Task(Name alias, Table<TaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private Task(Name alias, Table<TaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Task(Table<O> child, ForeignKey<O, TaskRecord> key) {
        super(child, key, TASK);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TaskRecord> getPrimaryKey() {
        return Keys.PK_TASK;
    }

    @Override
    public List<UniqueKey<TaskRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskRecord>>asList(Keys.PK_TASK);
    }

    @Override
    public Task as(String alias) {
        return new Task(DSL.name(alias), this);
    }

    @Override
    public Task as(Name alias) {
        return new Task(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Task rename(String name) {
        return new Task(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Task rename(Name name) {
        return new Task(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Long, String, Integer, Integer, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
