/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.dao;


import github.spritecn.swaggerTest.dao.tables.Apidoc;
import github.spritecn.swaggerTest.dao.tables.records.ApidocRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ApidocRecord, Integer> IDENTITY_APIDOC = Identities0.IDENTITY_APIDOC;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApidocRecord> PK_APIDOC = UniqueKeys0.PK_APIDOC;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ApidocRecord, Integer> IDENTITY_APIDOC = Internal.createIdentity(Apidoc.APIDOC, Apidoc.APIDOC.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ApidocRecord> PK_APIDOC = Internal.createUniqueKey(Apidoc.APIDOC, "pk_apiDoc", new TableField[] { Apidoc.APIDOC.ID }, true);
    }
}
