/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.dao;


import github.spritecn.swaggerTest.dao.tables.Apidoc;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>apiDoc</code>.
     */
    public static final Apidoc APIDOC = Apidoc.APIDOC;
}
