/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiEntity implements Serializable {

    private static final long serialVersionUID = 1872983796;

    private Integer id;
    private Long    lastUpdateTime;
    private Integer sourceId;
    private String  url;
    private String  tags;
    private Short   method;
    private Short   requestType;
    private Short   responseType;
    private String  requestTemplate;

    public ApiEntity() {}

    public ApiEntity(ApiEntity value) {
        this.id = value.id;
        this.lastUpdateTime = value.lastUpdateTime;
        this.sourceId = value.sourceId;
        this.url = value.url;
        this.tags = value.tags;
        this.method = value.method;
        this.requestType = value.requestType;
        this.responseType = value.responseType;
        this.requestTemplate = value.requestTemplate;
    }

    public ApiEntity(
        Integer id,
        Long    lastUpdateTime,
        Integer sourceId,
        String  url,
        String  tags,
        Short   method,
        Short   requestType,
        Short   responseType,
        String  requestTemplate
    ) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
        this.sourceId = sourceId;
        this.url = url;
        this.tags = tags;
        this.method = method;
        this.requestType = requestType;
        this.responseType = responseType;
        this.requestTemplate = requestTemplate;
    }

    public Integer getId() {
        return this.id;
    }

    public ApiEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public ApiEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public Integer getSourceId() {
        return this.sourceId;
    }

    public ApiEntity setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public ApiEntity setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getTags() {
        return this.tags;
    }

    public ApiEntity setTags(String tags) {
        this.tags = tags;
        return this;
    }

    public Short getMethod() {
        return this.method;
    }

    public ApiEntity setMethod(Short method) {
        this.method = method;
        return this;
    }

    public Short getRequestType() {
        return this.requestType;
    }

    public ApiEntity setRequestType(Short requestType) {
        this.requestType = requestType;
        return this;
    }

    public Short getResponseType() {
        return this.responseType;
    }

    public ApiEntity setResponseType(Short responseType) {
        this.responseType = responseType;
        return this;
    }

    public String getRequestTemplate() {
        return this.requestTemplate;
    }

    public ApiEntity setRequestTemplate(String requestTemplate) {
        this.requestTemplate = requestTemplate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApiEntity (");

        sb.append(id);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(sourceId);
        sb.append(", ").append(url);
        sb.append(", ").append(tags);
        sb.append(", ").append(method);
        sb.append(", ").append(requestType);
        sb.append(", ").append(responseType);
        sb.append(", ").append(requestTemplate);

        sb.append(")");
        return sb.toString();
    }
}
