/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigEntity implements Serializable {

    private static final long serialVersionUID = -391506258;

    private Integer id;
    private Long    lastUpdateTime;
    private Short   type;
    private String  name;
    private String  value;

    public ConfigEntity() {}

    public ConfigEntity(ConfigEntity value) {
        this.id = value.id;
        this.lastUpdateTime = value.lastUpdateTime;
        this.type = value.type;
        this.name = value.name;
        this.value = value.value;
    }

    public ConfigEntity(
        Integer id,
        Long    lastUpdateTime,
        Short   type,
        String  name,
        String  value
    ) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
        this.type = type;
        this.name = name;
        this.value = value;
    }

    public Integer getId() {
        return this.id;
    }

    public ConfigEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public ConfigEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public Short getType() {
        return this.type;
    }

    public ConfigEntity setType(Short type) {
        this.type = type;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public ConfigEntity setName(String name) {
        this.name = name;
        return this;
    }

    public String getValue() {
        return this.value;
    }

    public ConfigEntity setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfigEntity (");

        sb.append(id);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
