/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestEntity implements Serializable {

    private static final long serialVersionUID = -526999706;

    private Integer id;
    private Long    lastUpdateTime;
    private Integer taskId;
    private Long    startTime;
    private Long    endTime;
    private String  request;
    private String  response;
    private Integer statusCode;

    public RequestEntity() {}

    public RequestEntity(RequestEntity value) {
        this.id = value.id;
        this.lastUpdateTime = value.lastUpdateTime;
        this.taskId = value.taskId;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.request = value.request;
        this.response = value.response;
        this.statusCode = value.statusCode;
    }

    public RequestEntity(
        Integer id,
        Long    lastUpdateTime,
        Integer taskId,
        Long    startTime,
        Long    endTime,
        String  request,
        String  response,
        Integer statusCode
    ) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
        this.taskId = taskId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.request = request;
        this.response = response;
        this.statusCode = statusCode;
    }

    public Integer getId() {
        return this.id;
    }

    public RequestEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public RequestEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public Integer getTaskId() {
        return this.taskId;
    }

    public RequestEntity setTaskId(Integer taskId) {
        this.taskId = taskId;
        return this;
    }

    public Long getStartTime() {
        return this.startTime;
    }

    public RequestEntity setStartTime(Long startTime) {
        this.startTime = startTime;
        return this;
    }

    public Long getEndTime() {
        return this.endTime;
    }

    public RequestEntity setEndTime(Long endTime) {
        this.endTime = endTime;
        return this;
    }

    public String getRequest() {
        return this.request;
    }

    public RequestEntity setRequest(String request) {
        this.request = request;
        return this;
    }

    public String getResponse() {
        return this.response;
    }

    public RequestEntity setResponse(String response) {
        this.response = response;
        return this;
    }

    public Integer getStatusCode() {
        return this.statusCode;
    }

    public RequestEntity setStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequestEntity (");

        sb.append(id);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(taskId);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(request);
        sb.append(", ").append(response);
        sb.append(", ").append(statusCode);

        sb.append(")");
        return sb.toString();
    }
}
