/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RunningEntity implements Serializable {

    private static final long serialVersionUID = -1315550627;

    private Integer id;
    private Long    lastUpdateTime;
    private Integer groupId;
    private Integer failCount;
    private Integer passCount;
    private Long    startTime;
    private Long    endTime;

    public RunningEntity() {}

    public RunningEntity(RunningEntity value) {
        this.id = value.id;
        this.lastUpdateTime = value.lastUpdateTime;
        this.groupId = value.groupId;
        this.failCount = value.failCount;
        this.passCount = value.passCount;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
    }

    public RunningEntity(
        Integer id,
        Long    lastUpdateTime,
        Integer groupId,
        Integer failCount,
        Integer passCount,
        Long    startTime,
        Long    endTime
    ) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
        this.groupId = groupId;
        this.failCount = failCount;
        this.passCount = passCount;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Integer getId() {
        return this.id;
    }

    public RunningEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public RunningEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public RunningEntity setGroupId(Integer groupId) {
        this.groupId = groupId;
        return this;
    }

    public Integer getFailCount() {
        return this.failCount;
    }

    public RunningEntity setFailCount(Integer failCount) {
        this.failCount = failCount;
        return this;
    }

    public Integer getPassCount() {
        return this.passCount;
    }

    public RunningEntity setPassCount(Integer passCount) {
        this.passCount = passCount;
        return this;
    }

    public Long getStartTime() {
        return this.startTime;
    }

    public RunningEntity setStartTime(Long startTime) {
        this.startTime = startTime;
        return this;
    }

    public Long getEndTime() {
        return this.endTime;
    }

    public RunningEntity setEndTime(Long endTime) {
        this.endTime = endTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RunningEntity (");

        sb.append(id);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(groupId);
        sb.append(", ").append(failCount);
        sb.append(", ").append(passCount);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);

        sb.append(")");
        return sb.toString();
    }
}
