/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceEntity implements Serializable {

    private static final long serialVersionUID = 1266278967;

    private Integer id;
    private String  url;
    private String  name;
    private Short   invalid;
    private Long    lastUpdateTime;
    private Long    lastFetchTime;
    private Short   autoFetchInterval;
    private String  basePath;
    private String  host;

    public SourceEntity() {}

    public SourceEntity(SourceEntity value) {
        this.id = value.id;
        this.url = value.url;
        this.name = value.name;
        this.invalid = value.invalid;
        this.lastUpdateTime = value.lastUpdateTime;
        this.lastFetchTime = value.lastFetchTime;
        this.autoFetchInterval = value.autoFetchInterval;
        this.basePath = value.basePath;
        this.host = value.host;
    }

    public SourceEntity(
        Integer id,
        String  url,
        String  name,
        Short   invalid,
        Long    lastUpdateTime,
        Long    lastFetchTime,
        Short   autoFetchInterval,
        String  basePath,
        String  host
    ) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.invalid = invalid;
        this.lastUpdateTime = lastUpdateTime;
        this.lastFetchTime = lastFetchTime;
        this.autoFetchInterval = autoFetchInterval;
        this.basePath = basePath;
        this.host = host;
    }

    public Integer getId() {
        return this.id;
    }

    public SourceEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public SourceEntity setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public SourceEntity setName(String name) {
        this.name = name;
        return this;
    }

    public Short getInvalid() {
        return this.invalid;
    }

    public SourceEntity setInvalid(Short invalid) {
        this.invalid = invalid;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public SourceEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public Long getLastFetchTime() {
        return this.lastFetchTime;
    }

    public SourceEntity setLastFetchTime(Long lastFetchTime) {
        this.lastFetchTime = lastFetchTime;
        return this;
    }

    public Short getAutoFetchInterval() {
        return this.autoFetchInterval;
    }

    public SourceEntity setAutoFetchInterval(Short autoFetchInterval) {
        this.autoFetchInterval = autoFetchInterval;
        return this;
    }

    public String getBasePath() {
        return this.basePath;
    }

    public SourceEntity setBasePath(String basePath) {
        this.basePath = basePath;
        return this;
    }

    public String getHost() {
        return this.host;
    }

    public SourceEntity setHost(String host) {
        this.host = host;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SourceEntity (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(name);
        sb.append(", ").append(invalid);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(lastFetchTime);
        sb.append(", ").append(autoFetchInterval);
        sb.append(", ").append(basePath);
        sb.append(", ").append(host);

        sb.append(")");
        return sb.toString();
    }
}
