/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskGroupEntity implements Serializable {

    private static final long serialVersionUID = -1112892720;

    private Integer id;
    private Long    lastUpdateTime;
    private String  name;
    private String  corn;
    private Long    nextExecuteTime;
    private String  reportJson;

    public TaskGroupEntity() {}

    public TaskGroupEntity(TaskGroupEntity value) {
        this.id = value.id;
        this.lastUpdateTime = value.lastUpdateTime;
        this.name = value.name;
        this.corn = value.corn;
        this.nextExecuteTime = value.nextExecuteTime;
        this.reportJson = value.reportJson;
    }

    public TaskGroupEntity(
        Integer id,
        Long    lastUpdateTime,
        String  name,
        String  corn,
        Long    nextExecuteTime,
        String  reportJson
    ) {
        this.id = id;
        this.lastUpdateTime = lastUpdateTime;
        this.name = name;
        this.corn = corn;
        this.nextExecuteTime = nextExecuteTime;
        this.reportJson = reportJson;
    }

    public Integer getId() {
        return this.id;
    }

    public TaskGroupEntity setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public TaskGroupEntity setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public TaskGroupEntity setName(String name) {
        this.name = name;
        return this;
    }

    public String getCorn() {
        return this.corn;
    }

    public TaskGroupEntity setCorn(String corn) {
        this.corn = corn;
        return this;
    }

    public Long getNextExecuteTime() {
        return this.nextExecuteTime;
    }

    public TaskGroupEntity setNextExecuteTime(Long nextExecuteTime) {
        this.nextExecuteTime = nextExecuteTime;
        return this;
    }

    public String getReportJson() {
        return this.reportJson;
    }

    public TaskGroupEntity setReportJson(String reportJson) {
        this.reportJson = reportJson;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TaskGroupEntity (");

        sb.append(id);
        sb.append(", ").append(lastUpdateTime);
        sb.append(", ").append(name);
        sb.append(", ").append(corn);
        sb.append(", ").append(nextExecuteTime);
        sb.append(", ").append(reportJson);

        sb.append(")");
        return sb.toString();
    }
}
