/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.dao.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Apidoc implements Serializable {

    private static final long serialVersionUID = -800568032;

    private Integer id;
    private String  sourceurl;
    private String  name;
    private Integer invalid;
    private Integer lastupdatetime;
    private Integer lastfetchtime;
    private Integer lastfetchfailed;
    private Integer autofetchinterval;
    private String  basepath;
    private String  host;
    private String  schemes;

    public Apidoc() {}

    public Apidoc(Apidoc value) {
        this.id = value.id;
        this.sourceurl = value.sourceurl;
        this.name = value.name;
        this.invalid = value.invalid;
        this.lastupdatetime = value.lastupdatetime;
        this.lastfetchtime = value.lastfetchtime;
        this.lastfetchfailed = value.lastfetchfailed;
        this.autofetchinterval = value.autofetchinterval;
        this.basepath = value.basepath;
        this.host = value.host;
        this.schemes = value.schemes;
    }

    public Apidoc(
        Integer id,
        String  sourceurl,
        String  name,
        Integer invalid,
        Integer lastupdatetime,
        Integer lastfetchtime,
        Integer lastfetchfailed,
        Integer autofetchinterval,
        String  basepath,
        String  host,
        String  schemes
    ) {
        this.id = id;
        this.sourceurl = sourceurl;
        this.name = name;
        this.invalid = invalid;
        this.lastupdatetime = lastupdatetime;
        this.lastfetchtime = lastfetchtime;
        this.lastfetchfailed = lastfetchfailed;
        this.autofetchinterval = autofetchinterval;
        this.basepath = basepath;
        this.host = host;
        this.schemes = schemes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSourceurl() {
        return this.sourceurl;
    }

    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getInvalid() {
        return this.invalid;
    }

    public void setInvalid(Integer invalid) {
        this.invalid = invalid;
    }

    public Integer getLastupdatetime() {
        return this.lastupdatetime;
    }

    public void setLastupdatetime(Integer lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    public Integer getLastfetchtime() {
        return this.lastfetchtime;
    }

    public void setLastfetchtime(Integer lastfetchtime) {
        this.lastfetchtime = lastfetchtime;
    }

    public Integer getLastfetchfailed() {
        return this.lastfetchfailed;
    }

    public void setLastfetchfailed(Integer lastfetchfailed) {
        this.lastfetchfailed = lastfetchfailed;
    }

    public Integer getAutofetchinterval() {
        return this.autofetchinterval;
    }

    public void setAutofetchinterval(Integer autofetchinterval) {
        this.autofetchinterval = autofetchinterval;
    }

    public String getBasepath() {
        return this.basepath;
    }

    public void setBasepath(String basepath) {
        this.basepath = basepath;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getSchemes() {
        return this.schemes;
    }

    public void setSchemes(String schemes) {
        this.schemes = schemes;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Apidoc (");

        sb.append(id);
        sb.append(", ").append(sourceurl);
        sb.append(", ").append(name);
        sb.append(", ").append(invalid);
        sb.append(", ").append(lastupdatetime);
        sb.append(", ").append(lastfetchtime);
        sb.append(", ").append(lastfetchfailed);
        sb.append(", ").append(autofetchinterval);
        sb.append(", ").append(basepath);
        sb.append(", ").append(host);
        sb.append(", ").append(schemes);

        sb.append(")");
        return sb.toString();
    }
}
