/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository;


import github.spritecn.swaggerTest.repository.tables.Swagger;
import github.spritecn.swaggerTest.repository.tables.records.SwaggerRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SwaggerRecord, Integer> IDENTITY_SWAGGER = Identities0.IDENTITY_SWAGGER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SwaggerRecord> PK_SWAGGER = UniqueKeys0.PK_SWAGGER;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SwaggerRecord, Integer> IDENTITY_SWAGGER = Internal.createIdentity(Swagger.SWAGGER, Swagger.SWAGGER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<SwaggerRecord> PK_SWAGGER = Internal.createUniqueKey(Swagger.SWAGGER, "pk_swagger", new TableField[] { Swagger.SWAGGER.ID }, true);
    }
}
