/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository;


import github.spritecn.swaggerTest.repository.tables.Api;
import github.spritecn.swaggerTest.repository.tables.Config;
import github.spritecn.swaggerTest.repository.tables.Request;
import github.spritecn.swaggerTest.repository.tables.Running;
import github.spritecn.swaggerTest.repository.tables.Source;
import github.spritecn.swaggerTest.repository.tables.Task;
import github.spritecn.swaggerTest.repository.tables.TaskGroup;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>api</code>.
     */
    public static final Api API = Api.API;

    /**
     * The table <code>config</code>.
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * The table <code>request</code>.
     */
    public static final Request REQUEST = Request.REQUEST;

    /**
     * The table <code>running</code>.
     */
    public static final Running RUNNING = Running.RUNNING;

    /**
     * The table <code>source</code>.
     */
    public static final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>task_group</code>.
     */
    public static final TaskGroup TASK_GROUP = TaskGroup.TASK_GROUP;
}
