/*
 * This file is generated by jOOQ.
 */
package github.spritecn.swaggerTest.repository;


import github.spritecn.swaggerTest.repository.tables.Swagger;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>swagger</code>.
     */
    public static final Swagger SWAGGER = Swagger.SWAGGER;
}
